### PR TITLE
MAEC v4.1 Support

### PR DESCRIPTION
**Pull request by ikiril01**
* Adds support for the latest version of MAEC/CybOX (v4.1/v2.1, respectively)
* Fixes a few bugs
* Updates documentation to account for dependencies

### CODE REVIEW

**Comment by SteveClement** [comment]
I will test this later in the week and let you know if it works for our setup.

@botherder @jekil can you retrigger the travis-ci build it aborted due to a download timeout.

**Comment by jekil** [comment]
@SteveClement done. We know Travis has some networking issues in the last month and test are failing at random.

**Comment by jekil** [comment]
Thanks for contributing.

**Comment by jekil** [comment]
I had to revert 2fc07a6a64247a467b122f9b47768a987aa5df34 because it broke the mmdef report.

**Pull request merged**
