### PR TITLE
fixed bson importing issue

### PR DESCRIPTION
**Pull request by PickmanSec**
Please enter the commit message for your changes. Lines starting

### CODE REVIEW

**Comment by KillerInstinct** [comment]
What exactly is the issue? IIRC you should be using Pymongo's version of bson.

**Comment by jbremer** [comment]
Sorry, missed this PR before. @PickmanSec you do realize this does not actually fix anything, it is merely cleaning up the code, right? ;-)

**Comment by KillerInstinct** [comment]
Ahh derp, misread the file path. :)

**Comment by jbremer** [comment]
Still don't think the title represents the PR, but I like it nonetheless. Thanks!

**Pull request merged**
