### PR TITLE
Alternative machinery module for vSphere/ESXi with memory-dump support

### PR DESCRIPTION
**Pull request by jgajek**
This is a vSphere/ESX machinery module for the Cuckoo sandbox and is intended as an alternative to Cuckoo's ESX machinery module.

It adds full memory dump functionality during analysis, which is currently not supported by Cuckoo's LibVirt-based ESX module.

The module depends on the vSphere API Python Bindings provided by VMware (https://github.com/vmware/pyvmomi) which can be installed via pip:

sudo pip install --upgrade pyvmomi

### CODE REVIEW

**Comment by jbremer** [comment]
Looks good to me - thanks. Will need somebody to confirm all works fine though (just to make sure).

**Comment by jgajek** [comment]
No problem Juriaan.  I've been using it successfully for 2-3 months now, but mostly with Brad Spengler's modified Cuckoo build, so additional validation can't hurt.

**Comment by KillerInstinct** [comment]
I'll test this tomorrow. Does this work well with volatility profiles for Vmware Snapshot memory dumps?

**Comment by jgajek** [comment]
It should.  I tested it with Cuckoo's memory analysis module backed by Volatility 2.4 and it worked fine.

**Comment by KillerInstinct** [comment]
Neato, I believe I am running 2.3.x -- will check then. :)

**Comment by KillerInstinct** [comment]
I tested this with a few analyses now and it works as expected. I do have a few suggestions for changes though:

1) Squelch requests logs by adding the below code:
```
logging.getLogger("requests").setLevel(logging.WARNING)
```
Otherwise we see each HTTPS API request to the ESXi/vSphere server.

2) Replace the error handling when the config file doesn't have values. EG if I didn't specify a user in the config file, it will default to try to log in with root. I think this should be replaced with CuckooCriticalError(). I would do this for the port too. (You already do this for Host/Password config values anyways.)

3) Minor grammar fixes:
* In line 53 of the machinery file you state you are raise'ing CuckooMachineError when in fact you raise CuckooCriticalError
* If we don't have pyVmomi, the error message on line 36 doesn't have the "use pip install pyvmomi to install" message which is in other places of Cuckoo.

Going to let this burn in some, but functionally it works the same as esx machinery module, and this has the benefit of not relying on libvirt to update their code. EG I'd expect this to work with vSphere 6.x where libvirt is does not support this version.

Overall, it seems it loads slightly slower than libvirt, but its almost unnoticeable. I'm okay with that considering it produces less logs and has the ability to grab snapshots. However with Volatility 2.3.1 I am unable to get it to parse:

(Snipped this to relevant logs)
```
AddrSpaceError: No suitable address space mapping found
VMWareSnapshotFile: No base Address Space
VMWareSnapshotFile: Invalid VMware signature: -
```

Going to give volatility 2.4 a shot though. Anyways, will report back in a week or so once I have some bandwidth to see how it handles 5-8 VM's running at the same time. If all goes good I'd honestly suggest replacing the current esx machinery with this one.

PS: I tested on ESXi 5.5.

**Comment by KillerInstinct** [comment]
Oh and also, you have configuration options for memory profiles in the vcenter config, which is not yet supported by upstream. (I presume they are dev'ing that now based off the open PR's)

**Comment by KillerInstinct** [comment]
I'm not sure what the RNG is used for in the _dump_memory function. Seems like its being used to set the name of the snapshot, but ESXi appears to just name the snapshot +1 of the previous.

See below (I printed out the request arguments):
```
2015-07-23 09:28:25,562 [modules.machinery.vsphere] INFO: Downloading memory dump [Array01] Cuckoo01/Cuckoo01-Snapshot15.vmsn to /opt/cuckoo/storage/analyses/778/memory.dmp
{'dsName': 'Array01'}
{'Cookie': 'vmware_soap_session="52608b7e-3378-d1c2-72b1-fe70b0963367"; Path=/; HttpOnly; Secure;'}
https://[IP Address]:443/folder/Cuckoo01/Cuckoo01-Snapshot15.vmsn
2015-07-23 09:33:14,999 [modules.machinery.vsphere] INFO: Removing snapshot cuckoo_memdump_408 for machine Cuckoo01
```

**Comment by jgajek** [comment]
Thanks for the detailed feedback, Jeremy.  I will try to get your suggestions implemented and checked in today.  With regards to the random number generator -- it is just used to generate a snapshot name (cuckoo_memdump_XXX) to reduce the chance of naming conflicts on the vSphere server.

Regarding loading times, yes I would expect this one to load a bit slower.  It does some additional initialization checks to make sure that the snapshots for all defined VM guests were taken in powered on state.  The original ESX machinery module will just hang and time out if a powered off snapshot is used, which can be confusing the first few times you are bitten by this issue.

**Comment by KillerInstinct** [comment]
@jgajek The snapshot that is saved in my datastore does not get saved as the RNG name, it gets saved as Cuckoo01-Snapshot14, to which the next one would be saved as Cuckoo01-Snapshot15. Does yours actually save that name to the datastore? If so, what version of ESXi are you using?

**Comment by jgajek** [comment]
The files are named sequentially as you describe, but there is also a label attached to each snapshot.  You should be able to see the labels in Snapshot Manager.  The memory dump snapshots are deleted by the machinery module after downloading, so the chance of naming conflicts is small, but it is just a "just in case" thing.  Since I retrieve snapshots by label in the code, I wanted to avoid ambiguities as much as possible.

**Comment by KillerInstinct** [comment]
Ahh that make sense, in that case, I would suggest increasing the RNG, as setups with 50+VM's may have a higher chance of collision. I'd suggest 10000000-99999999 or something similar.

**Comment by jgajek** [comment]
Done.

**Comment by jbremer** [comment]
Thanks @jgajek and @KillerInstinct for the feedback!

**Comment by vpistillo** [comment]
When I run cuckoo I receive always the some error also if I run the command suggested (./utils/community.py -wafb monitor).

 2015-09-01 14:55:49,992 [root] WARNING: The binary analyzer/windows/bin/monitor-x86.dll is more than a week old! 2015-09-01 14:55:50,031 [root] WARNING: The binary analyzer/windows/bin/monitor-x64.dll is more than a week old!

2015-09-01 14:55:50,039 [root] WARNING: The binary analyzer/windows/bin/inject-x86.exe is more than a week old! 2015-09-01 14:55:50,048 [root] WARNING: The binary analyzer/windows/bin/inject-x64.exe is more than a week old!

2015-09-01 14:55:50,057 [root] WARNING: The binary analyzer/windows/bin/is32bit.exe is more than a week old!

2015-09-01 14:55:50,057 [root] CRITICAL: It is recommended that you update the binaries used for Windows analysis (if you have not done so already, it is possible that there was no update - in that case this error will persist). To do so, please run the following command: ./utils/community.py -wafb monitor.

**Comment by vpistillo** [comment]
When I run cuckoo I receive also the following INFO:

2015-09-02 11:22:04,404 [lib.cuckoo.core.scheduler] INFO: Using "vsphere" machine manager with max_analysis_count=0, max_machines_count=0, and max_vmstartup_count=10
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by vpistillo** [comment]
During the malware analysis I receive the following message:

2015-09-01 12:29:06,646 [modules.processing.dumptls] INFO: TLS Master secrets file not found for analysis

**Comment by jbremer** [comment]
@vpistillo Most of those are legitimate errors, but I'll try to make them more user friendly.

**Comment by jbremer** [comment]
@jgajek I may have been a bit prosperous with merging, we have a small follow-up question from the Cuckoo Foundation point of view, namely if you could sign a CLA for us. Feel free to email us at cuckoo@cuckoofoundation.org for more information and/or please check http://cuckoofoundation.org/contribute.html - thanks!

**Comment by jgajek** [comment]
Jurriaan, I will check with our senior management about signing the
agreement.

**Pull request merged**
