### PR TITLE
Provide WSGI application for API

### PR DESCRIPTION
**Pull request by seanthegeek**

### CODE REVIEW

**Comment by seanthegeek** [comment]
This allows the bottle-powered API to be used as a WSGI application in production web servers.

**Comment by vsantola** [comment]
There is a typo on utils/api.py line 414:

+# Provide WSGI application
+application = defualt_app()

**Comment by botherder** [comment]
Introduced manually.

**Comment by seanthegeek** [comment]
Thank you. Github was not allowing me to modify my own branch.

**Pull request closed without merging**
